### ISSUE TITLE
Suggestion: login switches or file

### ISSUE THREAD

**Issue by theDanielJLewis** [trs/shift-code#3]
It'd be great if this could didn't require re-entering login info every time. This could be done with `-e`/`--email` and `-p`/`--password`, read from a file, or from an environment variable.

**Comment by trs** [comment]
I'm fine with adding flags to bypass prompts, could even be extended into selecting the platform and game so it can be ran without any input.
I'd rather not support passwords in plain text files though.

**Comment by theDanielJLewis** [comment]
Oh yes on supporting the other choices! I forgot that your script does that.

**Comment by theDanielJLewis** [comment]
Please look at my commit #6, which adds arguments for email, password, platform, and game (with `games` eventually to support multiple games.

**Comment by trs** [comment]
v1.0.0 now supports login and storing the session.
