### ISSUE TITLE
Allow pasting of email/password

### ISSUE THREAD

**Issue by vertigo220** [trs/shift-code#36]
Perhaps this is a limitation of running inside the terminal, but normally text can be pasted into a terminal, so it seems it should be able to be done here as well. I use a password manager with long, complex passwords, as should everyone, and whenever something restricts pasting or autofill, whether it's a website or program, it essentially punishes and discourages the use of a password manager, which is definitely *not* what should be done. I'm not sure how long a session will be maintained, but I'm thinking this is something that could be run every month or two, and having to manually type my long password in each time would be annoying.

**Comment by trs** [comment]
Good password hygiene is great! I'm unsure why you're unable to paste your credentials. I use this on Windows 10 using [Windows Terminal](https://github.com/microsoft/terminal) and can paste just fine. The inputs are provided by the [prompts](https://github.com/terkelg/prompts) library and shouldn't have any sort of restriction applied.
