### ISSUE TITLE
Use .\@shift-code\cli\Data instead of %localappdata%\...

### ISSUE THREAD

**Issue by vertigo220** [trs/shift-code#37]
For all intents and purposes, this is essentially a "portable" app, even if it doesn't claim to be. There's no installation and it's a very basic command-line program, so the typical user, I would think, would expect that it would be more-or-less self-contained, which is why I was surprised to see it had created a series of folders and files in %localappdata%. I didn't even realize at first that it created any files, but when I saw that it did, I expected them to be in the same directory as the exe, and had to do a search to find them. There are two reasons the executable directory is better: it keeps it truly portable, preventing the placement of potentially undesired data (especially considering it holds the account session data) on a computer that the user may not have intended or wanted to do, and may not realize it did, and it makes it easier to find said data. At the very least, it should ask, on first run, where to store this data or, if you prefer to not use a menu prompting for user input, require a parameter to store it anywhere other than the exe directory.

**Comment by trs** [comment]
While I see your reasoning, I don't have any plans on supporting changing the cache path or adding a prompt. I encourage you to fork this to make any changes you see fit.
