### ISSUE TITLE
Consider replacement or additional code source?

### ISSUE THREAD

**Issue by theDanielJLewis** [trs/shift-code#7]
I've noticed several times that http://ticklemezombie.com/shift often doesn't have the latest codes. For example, a two-hour code was released Friday morning, but never appeared on the site. And today, there are two BL3 codes, but they're not on that site.

I suggest adding an additional source for codes. https://shift.orcicorn.com/ seems to be updated more often and might be worth pulling in, too.

**Comment by theDanielJLewis** [comment]
To illustrate the need for this, 5 codes were released in the last few days and 4 of them were for 12 or 24 hours. shift.orcicorn listed all 5, but ticklemezombie never listed them.

**Comment by theDanielJLewis** [comment]
Orcicorn offers RSS feeds, which may be easier to parse than scraping the page.

**Comment by theDanielJLewis** [comment]
Yup. The data source desperately needs to be changed. In the last week, there have been almost 10 golden keys, all visible on https://shift.orcicorn.com/, but they never showed up on ticklemezombie.

**Comment by trs** [comment]
I've been working on splitting this up into reusable libraries.

- Codes are fetched with https://github.com/trs/shift-code-observer
- Codes are redeemed with https://github.com/trs/shift-code-api

The [`1.0`](https://github.com/trs/shift-code-redeemer/tree/1.0) branch has the progress of implementing these.

**Comment by theDanielJLewis** [comment]
Great! I’ll checkout that branch soon.

**Comment by theDanielJLewis** [comment]
Maybe it's complete, or else I'm lost, but I can't figure out how to run the 1.0 branch.

**Comment by trs** [comment]
v1.0.0 uses https://shift.orcicorn.com/
